### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by dnephin**
Builds on #114 and #115

This PR adds a CircleCI config for running tests against the last 3 major versions of Go.

You can see a run against my branch here: https://app.circleci.com/pipelines/github/dnephin/go-metrics

The only thing that is missing is to add the project to CircleCI here: https://app.circleci.com/projects/

### CODE REVIEW

**Review by banks — APPROVED** [review]
Thanks Daniel!

**Comment by banks** [comment]
@armon I've merged this but I'm not repo admin so I can't add it in Circle CI. Could you do that please? In https://app.circleci.com/projects/. 

Daniel added the circle config here we just need to setup Circle's end to start tracking this repo.

**Comment by armon** [comment]
Done!

**Comment by dnephin** [comment]
Thank you!

**Comment by dnephin** [comment]
I see the first build failed with:

> Orb gotest/tools@0.0.13 not loaded. To use this orb, an organization admin must opt-in to using third party orbs in Organization Security settings.

It seems to be working on my PR, but I'm not sure if that is because I have circleCI enabled on my fork, with this setting enabled.

**Pull request merged**
