### PR TITLE
Fix counter metric types

### PR DESCRIPTION
**Pull request by discordianfish**
The following metrics are counters, not gauges:

- stats.Mallocs
- stats.Frees
- stats.PauseTotalNs
- stats.NumGC

### CODE REVIEW

**Comment by armon** [comment]
@discordianfish Counters have the behavior of summing, where a gauge will retain the last value, which makes more since since things like Total Pause and NumGC are already an aggregate, otherwise you would get a double summing.

**Comment by discordianfish** [comment]
Ah,  you mean setCounter actually increments the counter?

**Comment by armon** [comment]
@discordianfish Counters will accumulate typically, so metrics like `Sum` and `Count` will do rollups, where Gauge is a point value, which makes more sense for this type of information.

**Comment by discordianfish** [comment]
Okay, I guess this is then something statsd-specific. At least in Prometheus' sense they are counters, not gauges. Confusing.. :)

**Pull request closed without merging**
