### PR TITLE
Only build PrometheusSink on Go >=1.3.

### PR DESCRIPTION
**Pull request by juliusv**
This fixes https://github.com/prometheus/client_golang/issues/102

### CODE REVIEW

**Comment by dachary** [comment]
cute :-) :+1:

**Comment by armon** [comment]
Will this build _only_ on Go1.3 or on anything >= 1.3?

**Comment by armon** [comment]
I'm also tempted to move this to a sub-package to avoid breaking builds.

**Comment by juliusv** [comment]
This will build on anything >=1.3. See http://golang.org/pkg/go/build/:

    - ...
    - "go1.3", from Go version 1.3 onward
    - ...

Using sub-packages would work too, but this already removes the entire Prometheus file from anyone's build when they are using Go <1.3.

**Comment by armon** [comment]
Cool, merging for now. We can deal with sub-packages later.

**Pull request merged**
