### PR TITLE
return rate in endpoint's output

### PR DESCRIPTION
**Pull request by sakateka**
Hi!
I want to return the counter rate in endpoint's output.
They were filtered here https://github.com/armon/go-metrics/pull/54/commits/adf3becca609f61229a757e21f394cdce9c0e9e4#diff-6ae13e3df4402693e50a11db4212316dR73

### CODE REVIEW

**Comment by sakateka** [comment]
I think it's more correct to show the rate of increase in the value, not the counter.
A simple example is the number of requests per second, if the counter is incremented by one, then the growth rate is correct, but if the counter is increased by a certain amount of visits, then the growth rate is not correct.

**Comment by sakateka** [comment]
PTAL @kyhavlov (as creator https://github.com/armon/go-metrics/pull/54) @preetapan @slackpad @dadgar

**Comment by sakateka** [comment]
Someone look here please.

**Comment by preetapan** [comment]
@sakateka unless I am mistaken, the rate was removed because you have all the information to calculate it correctly by looking at two consecutive pairs of <LastUpdated,Count>.  @kyhavlov ?

**Comment by sakateka** [comment]
LastUpdated also filtered from json output https://github.com/armon/go-metrics/commit/adf3becca609f61229a757e21f394cdce9c0e9e4#diff-6ae13e3df4402693e50a11db4212316dR78
I not only return the `Rate`, but also adjust its calculation for the counters.
The `Rate` is always calculated, so include it in json output does not seem costly.
In any case, something needs to be returned to json :-)

**Comment by slackpad** [comment]
Talked this over with @kyhavlov and this does look more correct, and as this wasn't exposed before should not break folks unless they were getting samples manually from the inmem sink, which seems unlikely.

**Pull request merged**
