### PR TITLE
Add Circonus Sink

### PR DESCRIPTION
**Pull request by maier**

### CODE REVIEW

**Comment by slackpad** [comment]
@maier thanks for the PR! I'm seeing the tests not building locally with the latest head of circonus-gometrics:

```
james@workpad go-metrics(pr/33) $ go test ./...
# github.com/armon/go-metrics/circonus
circonus/circonus_test.go:23: cfg.CheckSubmissionURL undefined (type *Config has no field or method CheckSubmissionURL)
circonus/circonus_test.go:78: cfg.CheckSubmissionURL undefined (type *Config has no field or method CheckSubmissionURL)
circonus/circonus_test.go:106: cfg.CheckSubmissionURL undefined (type *Config has no field or method CheckSubmissionURL)
circonus/circonus_test.go:134: cfg.CheckSubmissionURL undefined (type *Config has no field or method CheckSubmissionURL)
```

Is there a change pending over on that side?

**Comment by maier** [comment]
My typo, all tests pass now for me.

```
⁖ go test
PASS
ok  	github.com/armon/go-metrics	0.360s
```

**Comment by maier** [comment]
Found another place in the test code I missed when I changed the configuration exposure. Now it passes the test run.

```
⁖ go test -v
=== RUN   TestNewCirconusSink
--- PASS: TestNewCirconusSink (0.00s)
=== RUN   TestFlattenKey
--- PASS: TestFlattenKey (0.00s)
=== RUN   TestSetGauge
--- PASS: TestSetGauge (0.00s)
=== RUN   TestIncrCounter
--- PASS: TestIncrCounter (0.00s)
=== RUN   TestAddSample
--- PASS: TestAddSample (0.00s)
PASS
ok  	github.com/armon/go-metrics/circonus	0.016s
```

**Comment by slackpad** [comment]
Thanks!

**Pull request merged**
