### PR TITLE
Fix race inmem

### PR DESCRIPTION
**Pull request by sakateka**
`InmemSink.Data` return pointer to current interval (alongside with others)
`InmemSink.getExistingInterval` also return current interval.
Client can write to it while read 'current' interval from intervals returned by `InmemSink.Data()`
We need create copy for current interval.

### CODE REVIEW

**Comment by sakateka** [comment]
@slackpad  PTAL

**Comment by sakateka** [comment]
I'm testing it in a production environment, the race fixed by this PR

**Comment by sakateka** [comment]
@dadgar PTAL

**Comment by dadgar** [comment]
Thanks @sakateka

**Pull request merged**
